#!/usr/bin/perl -w

# recursive ldd: calls ldd, parses its output, recalls ldd on each
# output library until all dependencies are resolved.

# Copyright (c) 2007 Andreas Bernauer, andreas@lysium.de
# Adapted from http://www.lysium.de/sw/ldd-rec.pl by @zzmp

my @check_queue = ();   # libs to check
my %checked_libs = ();    # libs already checked.
my %result = ();    # result
my $lib;      # current dependency library
my $code = 0;

$ENV{"LC_CTYPE"}="C";   # we match against English output of ldd

push @check_queue, @ARGV;

while (@check_queue) {
  my $to_check = pop @check_queue;
  if (exists $checked_libs{$to_check}) {
    next;
  } else {
    $checked_libs{$to_check} = 1;
  }

  my @libraries = `ldd $to_check`;
  foreach my $line (@libraries) {
    chomp $line;
    if ($line =~ / => (\S+) \(/      # mapped libraries
  or $line =~ /(\S+) \(/) {          # directly resolved libraries
      $lib = $1;
      $result{$lib} = 1;
      push @check_queue, $lib;
    } elsif ($line eq "\tstatically linked" # no library
       or $line eq"\tnot a dynamic executable"
#      or $line =~ /^.*:$/
      or $line =~ /linux-[(vdso)[(32)?|(64)?]|(gate)].so.1/) { # included by the kernel (@zzmp)
      next;
    } elsif ($line =~ /not found/) {
      $code = 1;
      print STDERR "$to_check: $line\n";
    } else {
      $code = 1;
      print STDERR "no match for '$line'\n";
    }
  }
}

#print "Dependencies:\n";
for (sort keys %result) {
  print $_, "\n";
}

exit "$code";

